Homework4
sls88/python_epam_2021 pull request #4
Opened 2021-03-14 12:23 UTC by sls88

2021-03-15 16:15 UTC, Aleksei-Samarin requested changes

2021-03-15 16:15 UTC, Aleksei-Samarin commented on hw/hw4/Homework_4_task1.py
> +            for stri in file:
Here we can delete nested block (reading data with further usage)

2021-03-15 16:15 UTC, Aleksei-Samarin commented on hw/hw4/Homework_4_task2.py
> +    except requests.exceptions.RequestException:
Can be simplified by importing RequestException

2021-03-15 16:15 UTC, Aleksei-Samarin commented on hw/hw4/Homework_4_task3.py
> +        sys.stderr.write(text)
These two conditions differs only on one object. Can we solve this with 2 lines?

2021-03-15 16:15 UTC, Aleksei-Samarin commented on requirements-dev.txt
> +requests
Add here only exact compatible versions without intervals

2021-03-15 16:15 UTC, Aleksei-Samarin commented on hw/hw4/Homework_4_task5.py
> +                        1 + i * 15,
Can we generate it programatically?

2021-03-15 18:14 UTC, AlbertGaz commented on hw/hw4/Homework_4_task2.py
> +    except requests.exceptions.RequestException:
Did you mean somethong like this?

dataflow = sys.stderr if text.startswith("error") else sys.stdout
dataflow.write(text)

2021-03-16 08:46 UTC, Aleksei-Samarin requested changes

2021-03-16 08:46 UTC, Aleksei-Samarin commented on requirements-dev.txt
> +certifi==2020.6.20
Do we need other packages except requests or it includes all of the rest packages?

2021-03-16 08:55 UTC, merged